const { cmd } = require("../command");
const axios = require("axios");

cmd(
  {
    pattern: "imagine",
    react: "🎨",
    desc: "Truly free AI generation (No API keys)",
    category: "ai",
    filename: __filename,
  },
  async (conn, m) => {
    const prompt = m.text.replace(/^\.?imagine\s*/i, "").trim();
    if (!prompt) return await m.reply("Example: .imagine a dragon");

    try {
      await m.reply("🌐 Using community GPUs...");

      // Start generation (no API key)
      const { data } = await axios.post(
        "https://stablehorde.net/api/v2/generate/async",
        {
          prompt: `4k, high quality, ${prompt}`,
          params: { width: 512, height: 512, steps: 25 }
        },
        { headers: { "apikey": "0000000000" } }
      );

      // Check status
      let result;
      for (let i = 0; i < 12; i++) { // Max 1 min wait
        await new Promise(resolve => setTimeout(resolve, 5000));
        result = await axios.get(`https://stablehorde.net/api/v2/generate/status/${data.id}`);
        if (result.data.done) break;
      }

      if (!result?.data?.generations?.[0]?.img) throw new Error("Timeout");
      
      await conn.sendMessage(
        m.chat,
        { 
          image: Buffer.from(result.data.generations[0].img, 'base64'),
          caption: `🎨 "${prompt}"\nGenerated by Stable Horde`
        },
        { quoted: m }
      );

    } catch (err) {
      await m.reply(`❌ ${err.message}\nTip: Try simpler prompts during peak times`);
    }
  }
);
