const { cmd } = require("../command");
const axios = require("axios");

cmd(
  {
    pattern: "imggen",
    alias: ["imagegen", "aiimage", "draw"],
    react: "🎨",
    desc: "Generate AI image from a text prompt",
    category: "ai",
    filename: __filename,
  },
  async (robin, mek, m, { from, q, reply }) => {
    try {
      if (!q) return reply("*Please enter a prompt to generate an image.* 🎨\n\nExample: imggen a cyberpunk samurai in Tokyo");

      reply("🧠 *Generating image...*\nThis may take a few seconds...");

      // Call Lexica API (no key needed)
      const res = await axios.get(`https://lexica.art/api/v1/search?q=${encodeURIComponent(q)}`);
      const results = res.data.images;

      if (!results || results.length === 0) {
        return reply("❌ No image found for that prompt. Try a different one!");
      }

      const img = results[Math.floor(Math.random() * results.length)].srcSmall;

      await robin.sendMessage(
        from,
        {
          image: { url: img },
          caption: `🖼️ *Prompt:* ${q}\n🔗 *Generated by Lexica AI*`,
        },
        { quoted: mek }
      );
    } catch (e) {
      console.error("ImageGen error:", e);
      reply(`❌ *Failed to generate image.*\nReason: ${e.message || e}`);
    }
  }
);
